//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Grass7 Setup.rc
//

// Icons
#define IDI_ICON				100
#define IDI_SMALL				101

// Bitmaps
#define IDB_BACKGROUND_BMP		201
#define IDB_FAKEWND_BMP			202

#define IDB_BACK_BTN1_BMP		203
#define IDB_BACK_BTN2_BMP		204
#define IDB_BACK_BTN3_BMP		206
#define IDB_BACK_BTN4_BMP		207

#define IDB_CLOSE_BTN1_BMP		208
#define IDB_CLOSE_BTN2_BMP		209
#define IDB_CLOSE_BTN3_BMP		211
#define IDB_CLOSE_BTN4_BMP		212

#define IDB_NORMAL_BTN1_BMP		213
#define IDB_NORMAL_BTN2_BMP		214
#define IDB_NORMAL_BTN3_BMP		216
#define IDB_NORMAL_BTN4_BMP		217

#define IDB_AUTOPART_BTN1_BMP	218
#define IDB_AUTOPART_BTN2_BMP	219
#define IDB_AUTOPART_BTN3_BMP	220
#define IDB_AUTOPART_BTN4_BMP	221

#define IDB_MANUALPART_BTN1_BMP	222
#define IDB_MANUALPART_BTN2_BMP	223
#define IDB_MANUALPART_BTN3_BMP	224
#define IDB_MANUALPART_BTN4_BMP	225

#define IDB_BANNER_BMP			226
#define IDB_SMALLLOGO_BMP		227
#define IDB_BOTTOM_PANEL_BMP	228
#define IDB_CHECKMARK_BMP		229

// Dialogs
#define IDD_PARENTPAGE			300
#define IDD_WELCOMEPAGE			301
#define IDD_LICENSEPAGE			302
#define IDD_CHANGELOGPAGE		303
#define IDD_PARTITIONPAGE		304
#define IDD_INSTALLINGPAGE		305
#define IDD_RESTARTINGPAGE		306

// Strings
#define IDS_APP_TITLE			400
#define IDS_TITLEBAR			401
#define IDS_PROGBAR_TEXT1		402
#define IDS_PROGBAR_TEXT2		403
#define IDS_NEXTBTN				404
#define IDS_INSTALLBTN			405
#define IDS_EULA_TITLE			406
#define IDS_CHANGELOG_TITLE		407
#define IDS_PARTITION_TITLE		408
#define IDS_INSTALLOPT_TITLE	409
#define IDS_COLLECTING_INFO     410
#define IDS_COPYING_FILES       411
#define IDS_EXPANDING_FILES     412
#define IDS_INSTALLING_FEATURES 413
#define IDS_INSTALLING_UPDATES  414
#define IDS_INSTALLING_TITLE	415
#define IDS_RESTARTING_TITLE	416
#define IDS_AUTOPARTBTN			417
#define IDS_MANUALPARTBTN		418
#define IDS_COMPATIBILITY_ERR	419
#define IDS_WINPE_REQUIRED_ERR	420
#define IDS_NO_INSTALL_IMG_ERR	421
#define IDS_IMG_APPLY_ERR		422
#define IDS_SETUP_EXIT			423
#define IDS_SETUP_EXIT_PROGRESS	424

// Buttons
#define ID_BACKBTN			    500
#define ID_CLOSEBTN			    501
#define ID_NORMALBTN			502
#define ID_AUTOMATICPARTBTN		503
#define ID_MANUALPARTBTN		504

// Window Messages
#define IDM_EXIT				600
#define MAINWND_CREATE_PROG_BAR	601
#define MAINWND_UPDATE_INSTALLING_PROG_BAR	602
#define SETUPWND_UPDATE_DIALOG	605
#define SETUPWND_INSTALL_FINISH	606
#define BTN_DISABLE				607
#define BTN_ENABLE				608
#define BTN_UPDATE				609
#define MAINWND_UPDATE_COLLECT_INFO_PROG_BAR 610
#define SETUPWND_RESTARTING_TIMER 611

// Progress Bar
#define ID_SMOOTHPROGRESSCTRL   700

// Check boxes
#define ID_ACCEPT_LICENSE		800

#ifndef IDC_STATIC
#define IDC_STATIC				-1
#endif
// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif
